"""Initial Schema

Revision ID: 7d904398159f
Revises: 
Create Date: 2026-03-06 19:02:03.650713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d904398159f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('habit_completions_habit_id_fkey'), 'habit_completions', type_='foreignkey')
    op.create_foreign_key(None, 'habit_completions', 'habits', ['habit_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'habit_completions', type_='foreignkey')
    op.create_foreign_key(op.f('habit_completions_habit_id_fkey'), 'habit_completions', 'habits', ['habit_id'], ['id'])
    # ### end Alembic commands ###
